
services:
  app:
    build: .
    container_name: DeskPet
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/log
    environment:
      # Passando as variáveis que o código Java irá procurar
      DB_HOST: postgres
      DB_NAME: "deskpet"
      DB_USER: "postgres"
      DB_PASS: "94786422Wp$"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db_postgres
    environment:
      POSTGRES_DB: "deskpet"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "94786422Wp$"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: